routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('galleries', 'GalleriesController');
Route::resource('videos', 'VideoController');
Route::resource('users', 'UserController');
Route::resource('phone', 'PhoneController');
Route::resource('comments', 'CommentController');
Route::resource('post', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{

    protected $fillable = [
        'name',

    ];

    public function comments(){

        return $this->hasMany('App\Comment');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Comment;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::latest()->paginate(5);
        return view('post.index',compact('posts'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        //$comments = Comment::all();
        return view('post.create',compact('comments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $post = new Post;
        $post->name= $request->name;
        $post->save();
        //$post->user()->save();
        // $user->post()->save($post);


        return redirect(route('post.index'))->withMessage('post Added');

    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {


        $post = Post::find($id);
       return view('post.show')->with('post',$post);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::where('id',$id)->first();
        return view('post.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $post =Post::find($id);
        $post->name= $request->name;
        $post->save();

        return redirect(route('post.index'))->withMessage('posts Is Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Post::where('id',$id)->delete();
        return redirect()->back()->withMessage('post Is Deleted');
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                    <div class="panel-heading"><h3 style="text-align: center">Post Create Form</h3>
                    </div>

                    <div class="panel-body">
                        <form class="form-horizontal" method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <label for="name" class="col-md-4 control-label">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" >
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('post.index') }}" class=" btn btn-danger">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div class="panel-heading"><h3 style="text-align: center">Post Create Form</h3>
                    <div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">{{ session('message') }}</div>

                </div>

                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('post.update',$post->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name"  value="{{ $post->name }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">

                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a href="{{ route('post.index') }}" class=" btn btn-danger">Back</a>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="panel-heading">
        <h5 style="text-align: center">post Lists <a href="{{ route('post.create') }}" class=" btn btn-danger pull-right">Add New post</a></h5>
        <div style="background:#00b38f; color: #ffffff; width: 600px;text-align: center; font-size: 20px;">{{ session('message') }}</div>


    </div>
    <table id="example1" class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>S.No</th>
            <th>Name</th>

            <th>Action</th>

        </tr>
        </thead>
        <tbody>

        @foreach($posts as $post)

            <tr>
                <td>{{ $loop->index + 1}}</td>

                {{--<td><a href=" {{ $post->link }}"><img style="height: 200px; width: 200px" src="{{storage_path('app/public'.$post->image)}}"></a></td>--}}

                <td>{{ $post->name }}</td>

                <td> <a href="{{ route('post.show',$post->id) }}" class=" btn btn-danger"><span class=" glyphicon glyphicon-eye-open"></span></a>
                    <a href="{{ route('post.edit',$post->id) }}" class=" btn btn-info"><span class="glyphicon glyphicon-edit"></span></a>
                    <form id="delete-form-{{ $post->id }}" method="POST" action="{{ route('post.destroy',$post->id) }}" style="display: none">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                    </form>
                    <a href="" onclick="
                            if(confirm('Are you sure, You went to delete this?'))

                            {
                            event.preventDefault();
                            document.getElementById('delete-form-{{ $post->id }}').submit();
                            }
                            else{
                            event.preventDefault();
                            }
                            " class=" btn btn-info"><span class="glyphicon glyphicon-trash"></span></a>

                </td>


            </tr>
        @endforeach

        </tbody>

    </table>

    {{ $posts->links() }}

@endsection

resources/views/post/show.blade.php
    @extends('layouts.app')

    {{-- Page title --}}

@section('content')

    <div class="row">
        {{--<div class="col-lg-12">--}}
            {{--<h1 class="page-header">Post</h1>--}}
        {{--</div>--}}
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                {{--<div class="panel-heading">--}}
                  {{--Post Information--}}
                {{--</div>--}}
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <tbody>
                            <tr>
                                <td style="text-align: center;color:darkblue"> <h3>{{ $post->name }}</h3> </td>
                            </tr>

                            </tbody>

                        </table>
                        <div class="row">
                        <div class="col-md-8 col-md-offset-4">

                                    @foreach($post->comments as $comment)
                                        <tr>
                                            <td ><b>Comment</b><br/></td>
                                        </tr>
                                         <tr>
                                            <td>{{ $comment->comment }}<br/></td>
                                        </tr>
                                    @endforeach
                                </div>
                        </div>

                        <form class="form-horizontal" method="POST" action="{{ route('comments.store') }}">
                            {{ csrf_field() }}

                            <input type="hidden" name="post_id" class="form-control" value="{{ $post->id}}">

                            <div class="form-group">
                                <label for="comment" class="col-md-4 control-label">Comment</label>

                                <div class="col-md-4">
                                    <input id="comment" type="text" class="form-control" name="comment" >
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                   <button type="submit" class="btn btn-primary"> Submit</button>
                                   {{--<button type="submit" class="btn btn-primary">Submit</button>--}}

                                </div>
                            </div>
                        </form>
                    </div>


                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection