routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('galleries', 'GalleriesController');
Route::resource('videos', 'VideoController');
Route::resource('users', 'UserController');
Route::resource('phone', 'PhoneController');
Route::resource('comments', 'CommentController');
Route::resource('post', 'PostController');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable= [
         'post_id','comment',
    ];

    public function post(){

        return $this->belongsTo('App\Post');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Comment;
class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $comments = Comment::latest()->paginate(5);
        return view('comments.index', compact('comments'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $posts = Post::all();
        return view('comments.create', compact('posts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'post_id' => 'required|exists:posts,id',
            'comment' => 'required',
        ]);


        $post = Post::find($request->post_id);
        $post->comments()->create([
            'comment'=> $request->comment

        ]);
//    <___________________________________>
//      //  dd($post->comments());
////        $comment = new Comment;
////
////        $comment->comment = $request->comment;
////        $comment->post_id = $request->post_id;
////        $comment->save();
//       // $comment->post()->save();
//         <___________________________________>
//



      return redirect(route('comments.index'))->withMessage('Comment Added');

    }


    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $comment = Comment::find($id);
        return view('comments.show')->with('comment', $comment);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $comment = Comment::where('id', $id)->first();
        return view('comments.edit', compact('comment'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $comment = Comment::find($id);
        $comment->comment = $request->comment;
        $comment->post_id = $request->post_id;
        $comment->save();

        return redirect(route('comments.index'))->withMessage('comments Is Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Comment::where('id', $id)->delete();
        return redirect()->back()->withMessage('comment Is Deleted');
    }
}

resources/views/comments/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                    <div class="panel-heading"><h3 style="text-align: center">Comment Create Form</h3>
                    </div>

                    <div class="panel-body">

                        <div class=" col-lg-offset-3 col-lg-6">
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                        <form class="form-horizontal" method="POST" action="{{ route('comments.store') }}" enctype="multipart/form-data">
                            {{ csrf_field() }}




                            <div class="form-group">
                                <label for="comment" class="col-md-4 control-label">comment</label>

                                <div class="col-md-6">
                                    <input id="comment" type="text" class="form-control" name="comment" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label>Select Id</label>
                                <select class="form-control select2 select2-hidden-accessible" data-placeholder="Select a State" style="width: 100%;" tabindex="-1" aria-hidden="true" name="post_id">
                                    @foreach($posts as $post)
                                        <option value="{{ $post->id }}">{{ $post->name}}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">

                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <a href="{{ route('comments.index') }}" class=" btn btn-danger">Back</a>
                                </div>
                            </div>
                        </form>
                    </div>

            </div>
        </div>
    </div>
@endsection

resources/views/comments/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-2">
                <div class="panel-heading"><h5 style="text-align: center">Slider Edit Form</h5></div>


                <div class="panel-body">
                    <form class="form-horizontal" method="POST" action="{{ route('comments.update',$comment->id) }}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}
                        <div class="form-group">
                            <label for="post_id" class="col-md-4 control-label">Post Id</label>

                            <div class="col-md-6">
                                <input id="post_id" type="number" class="form-control" name="post_id" value="{{ $comment->post_id }}">
                        </div>
                        </div>
                        <div class="form-group">
                            <label for="comment" class="col-md-4 control-label">Comment</label>

                            <div class="col-md-6">
                                <input id="comment" type="text" class="form-control" name="comment" value="{{ $comment->comment }}" >
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">

                                <button type="submit" class="btn btn-primary">Submit</button>

                                <a href="{{ route('comments.create') }}" class=" btn btn-danger">Create</a>
                                <a href="{{ route('comments.index') }}" class=" btn btn-danger">Comment</a>
                            </div>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/comments/index.blade.php
@extends('layouts.app')

{{-- Page title --}}
@section('title', 'Many To Many')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">comments
                <a href="{{ url('/comments/create') }}" class="btn btn-primary btn-xs" title="Add New Gallery"><span class="glyphicon glyphicon-plus" aria-hidden="true"/></a></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">

                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        @include('layouts.alert')
                        <table class="table table-striped table-bordered table-hover" id="dataTables">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th> {{ trans('Post_name') }} </th>
                                <th> {{ trans('comment') }} </th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $x=1; @endphp
                            @foreach($comments as $item)
                                <tr>
                                    <td>{{ $x++ }}</td>
                                    <td>{{ $item->post->name }}</td>-
                                    <td>{{ $item->comment }}</td>
                                    <td>
                                        <a href="{{ url('/comments/' . $item->id) }}" class="btn btn-success btn-xs" title="View Gallery"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"/></a>
                                        <a href="{{ url('/comments/' . $item->id . '/edit') }}" class="btn btn-primary btn-xs"
                                           title="Edit comments"><span class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
                                        {!! Form::open([
                                            'method'=>'DELETE',
                                            'url' => ['/comments', $item->id],
                                            'style' => 'display:inline'
                                        ]) !!}
                                        {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete Gallery" />', array(
                                            'type' => 'submit',
                                            'class' => 'btn btn-danger btn-xs',
                                            'title' => 'Delete comments',
                                            'onclick'=>'return confirm("Are you sure you want to delete ' . $item->name . '?")'
                                        )) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="pagination"> {!! $comments->render() !!} </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

resources/views/comments/show.blade.php
@extends('layouts.app')

{{-- Page title --}}

@section('content')


    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    comment Information
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <tbody>
                            <tr>
                                <th> {{ trans('Comment') }} </th>
                                <td> {{ $comment->comment }} </td>
                            </tr>
                            <tr>
                                <th> {{ trans('Post Id') }} </th>
                                <td> {{ $comment->post_id }} </td>
                            </tr>

                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="2" class="text-right">
                                    <a href="{{ url('comments/' . $comment->id . '/edit') }}"
                                       class="btn btn-primary btn-xs" title="Edit User"><span
                                                class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
                                    {!! Form::open([
                                        'method'=>'DELETE',
                                        'url' => ['comments', $comment->id],
                                        'style' => 'display:inline'
                                    ]) !!}
                                    {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"/>', array(
                                            'type' => 'submit',
                                            'class' => 'btn btn-danger btn-xs',
                                            'title' => 'Delete User',
                                            'onclick'=>'return confirm("Are you sure you want to delete ' . $comment->name . '?")'
                                    )) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>


                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection