routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('galleries', 'GalleriesController');
Route::resource('videos', 'VideoController');
Route::resource('users', 'UserController');
Route::resource('phone', 'PhoneController');
Route::resource('comments', 'CommentController');
Route::resource('post', 'PostController');

app/Phone.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    protected $fillable = [
        'phone', 'user_id',
    ];

    public function user(){

        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Phone;
use App\User;
class PhoneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $phones = Phone::latest()->paginate(5);
        return view('phone.index',compact('phones','user'));

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

         $users = User::all();
        return view('phone.create',compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'user_id' => 'required|exists:users,id',
            'phone' => 'required',
        ]);

        $user = User::find($request->user_id);
      //  $phone = new phone;
        //$phone->user_id = $request->user_id;
       // $phone->phone = $request->phone;
       // $phone->save();
       //$user->phone()->save($phone);


      $user->phone()->create(['phone' =>$request->phone]);


       // Phone::create($request->all());
//        Phone::create([
//
//            'user_id'=>$request->user_id,
//            'phone'=>$request->phone,
//
//        ]);


        return redirect(route('phone.index'))->withMessage('Phone Added');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $phone = Phone::find($id);
        return view('phones.show')->with('phones',$phone);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $phone = Phone::where('id',$id)->first();
        return view('phones.edit',compact('phone'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $phone = phone::find($id);
        $phone->phone = $request->phone;
        $phone->save();

        return redirect(route('phones.index'))->withMessage('phones Is Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Phone::where('id',$id)->delete();
        return redirect()->back()->withMessage('phone Is Deleted');
    }
}

resources/views/phone/create.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Phone Add Form


                </div>

    <form role="form" action="{{ route('phone.store') }}" method="POST">
        {{ csrf_field() }}
        <div class="box-body">

            <div class=" col-lg-offset-3 col-lg-6">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="form-group">
                    <label>Select Id</label>
                    <select class="form-control select2 select2-hidden-accessible" data-placeholder="Select a State" style="width: 100%;" tabindex="-1" aria-hidden="true" name="user_id">
                        @foreach($users as $user)
                            <option value="{{ $user->id }}">{{ $user->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="number" class="form-control" id="phone"  name="phone" placeholder="phone">
                </div>




                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a  href="{{ route('phone.index') }}" class="btn btn-warning">Back</a>
                </div>
            </div>

        </div>


     </form>
        <!-- /.col-lg-12 -->
    </div>



@endsection

resources/views/phone/edit.blade.php
@extends('layouts.app')

{{-- Page title --}}
@section('title', 'Edit' . $gallery->name )

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Edit {{ $gallery->name }}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Gallery Edit Form
                </div>
                <div class="panel-body">
                    {!! Form::model($gallery, [
                        'method' => 'PATCH',
                        'url' => ['/galleries', $gallery->id],
                        'class' => 'form-horizontal'
                    ]) !!}

                    @include('galleries.form')

                    {!! Form::close() !!}
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

resources/views/phone/form.blade.php
@include('layouts.alert')

<div class="form-group {{ $errors->has('phone') ? 'has-error' : ''}}">
    {!! Form::label('phone', trans('phone.name'), ['class' => 'col-sm-3 control-label']) !!}
    <div class="col-sm-9">
        {!! Form::number('phone', null, ['class' => 'form-control', 'required' => 'required']) !!}
        {!! $errors->first('phone', '<p class="help-block">:message</p>') !!}
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-3 col-sm-3">
        {!! Form::submit('Save', ['class' => 'btn btn-primary form-control']) !!}
    </div>
</div>

resources/views/phone/index.blade.php
@extends('layouts.app')

{{-- Page title --}}
@section('title', 'Many To Many')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Phone Number
                <a href="{{ url('/phone/create') }}" class="btn btn-primary btn-xs" title="Add New Gallery"><span class="glyphicon glyphicon-plus" aria-hidden="true"/></a></h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Phone List
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        @include('layouts.alert')
                        <table class="table table-striped table-bordered table-hover" id="dataTables">
                            <thead>
                            <tr>
                                <th>S.No</th>
                                <th> {{ trans('User Name') }} </th>
                                <th> {{ trans('Phone.Number') }} </th>

                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @php $x=1; @endphp
                            @foreach($phones as $item)
                                <tr>
                                    <td>{{ $x++ }}</td>
                                    <td>{{ $item->user->name}}</td>
                                    <td>{{ $item->phone }}</td>

                                    <td>
                                        <a href="{{ url('/phone/' . $item->id) }}" class="btn btn-success btn-xs" title="View Gallery"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"/></a>
                                        <a href="{{ url('/phone/' . $item->id . '/edit') }}" class="btn btn-primary btn-xs"
                                           title="Edit phone"><span class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
                                        {!! Form::open([
                                            'method'=>'DELETE',
                                            'url' => ['/phone', $item->id],
                                            'style' => 'display:inline'
                                        ]) !!}
                                        {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true" title="Delete Gallery" />', array(
                                            'type' => 'submit',
                                            'class' => 'btn btn-danger btn-xs',
                                            'title' => 'Delete phone',
                                            'onclick'=>'return confirm("Are you sure you want to delete ' . $item->name . '?")'
                                        )) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <div class="pagination"> {!! $phones->render() !!} </div>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection

resources/views/phone/show.blade.php
@extends('layouts.app')

{{-- Page title --}}
@section('title')
    {{ $gallery->name }}
    @parent
@stop

@section('content')

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{ $gallery->name }}</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Gallery Information
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped table-hover">
                            <tbody>
                            <tr>
                                <th> {{ trans('galleries.name') }} </th>
                                <td> {{ $gallery->name }} </td>
                            </tr>
                            <tr>
                                <th> {{ trans('galleries.description') }} </th>
                                <td> {{ $gallery->description }} </td>
                            </tr>
                            <tr>
                                <th> {{ trans('galleries.display') }} </th>
                                <td> {{ $gallery->display === 'N' ? 'No' : 'Yes' }} </td>
                            </tr>
                            <tr>
                                <th> {{ trans('common.created_at') }} </th>
                                <td> {{ $gallery->created_at->toDayDateTimeString() }} </td>
                            </tr>
                            <tr>
                                <th> {{ trans('common.updated_at') }} </th>
                                <td> {{ $gallery->updated_at->diffForHumans() }} </td>
                            </tr>
                            </tbody>
                            <tfoot>
                            <tr>
                                <td colspan="2" class="text-right">
                                    <a href="{{ url('galleries/' . $gallery->id . '/edit') }}"
                                       class="btn btn-primary btn-xs" title="Edit User"><span
                                                class="glyphicon glyphicon-pencil" aria-hidden="true"/></a>
                                    {!! Form::open([
                                        'method'=>'DELETE',
                                        'url' => ['galleries', $gallery->id],
                                        'style' => 'display:inline'
                                    ]) !!}
                                    {!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"/>', array(
                                            'type' => 'submit',
                                            'class' => 'btn btn-danger btn-xs',
                                            'title' => 'Delete User',
                                            'onclick'=>'return confirm("Are you sure you want to delete ' . $gallery->name . '?")'
                                    )) !!}
                                    {!! Form::close() !!}
                                </td>
                            </tr>
                            </tfoot>
                        </table>
                    </div>

                    @if(count($videos) > 0)
                        <div class="row">
                            @foreach($videos as $row)
                                <div class="col-md-4">
                                    <div class="panel panel-{{ $row->display === 'N' ? 'danger' : 'default'}}">
                                        <div class="panel-heading">
                                            <h3 class="panel-title">{{ $row->title }}</h3>
                                        </div>
                                        <div class="panel-body">
                                            <div class="embed-responsive embed-responsive-16by9">
                                                @if($row->provider === 'F')
                                                    <div class="fb-video embed-responsive-item"
                                                         data-href="{{ $row->source }}"
                                                         data-allowfullscreen="true"></div>
                                                @else
                                                    <iframe class="embed-responsive-item" src="{{ $row->source }}"
                                                            allowfullscreen></iframe>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    @endif
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
@endsection