routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('galleries', 'GalleriesController');
Route::resource('videos', 'VideoController');
Route::resource('users', 'UserController');
Route::resource('phone', 'PhoneController');
Route::resource('comments', 'CommentController');
Route::resource('post', 'PostController');

resources/views/layouts/alert.blade.php
@if(Session::has('message'))
    <div class="alert {{ Session::get('alert-class', 'alert-success') }} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ Session::get('message') }}
    </div>
@endif
@if ($errors->any())
    @foreach ($errors->all() as $error)
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ $error }}
        </div>
    @endforeach
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

   <h1 style="text-align: center;color: #259d6d"> @yield('title') </h1>
    <!-- Styles -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">



</head>
<body>
    <div id="app">
        @include('layouts.nav')


        @yield('content')
    </div>




    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    @stack('scripts')
</body>

</html>

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    @include('layouts.nav')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
             @yield('content')
            </div>
        </div>
    </div>
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>

@stack('scripts')
</body>

</html>

resources/views/layouts/nav.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            {{--<a class="navbar-brand" href="{{ url('/') }}">--}}
            {{--{{ config('app.name', 'Laravel') }}--}}
            {{--</a>--}}
            {{--<a href="{{ route('home') }}">--}}
            {{--<img src="{{ asset('images/icc.png') }}" alt="CCCL">--}}
            {{--</a>--}}
            <ul class="nav navbar-nav navbar-reft">
                <li><a href="{{ route('users.index') }}" class="bg-{{ (request()->segment(1) == 'Galleries' ? 'danger' : 'info') }}"><b>User</b></a></li>
                <li><a href="{{ route('phone.index') }}" class="bg-{{ (request()->segment(1) == 'videos' ? 'danger' : 'info') }}"><b>Phone</b></a></li>
                <li><a href="{{ route('galleries.index') }}" class="bg-{{ (request()->segment(1) == 'Galleries' ? 'danger' : 'info') }}"><b>Gallery</b></a></li>
                <li><a href="{{ route('videos.index') }}" class="bg-{{ (request()->segment(1) == 'videos' ? 'danger' : 'info') }}"><b>Video</b></a></li>
                <li><a href="{{ route('post.index') }}" class="bg-{{ (request()->segment(1) == 'Galleries' ? 'danger' : 'info') }}"><b>Post</b></a></li>
                <li><a href="{{ route('comments.index') }}" class="bg-{{ (request()->segment(1) == 'videos' ? 'danger' : 'info') }}"><b>Comment</b></a></li>

            </ul>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                &nbsp;
            </ul>

            <!-- Right Side Of Navbar -->
            {{--<ul class="nav navbar-nav navbar-right">--}}
                {{--<!-- Authentication Links -->--}}
                {{--@guest--}}
                {{--<li><a href="{{ route('login') }}"><b>Login</b></a></li>--}}
                {{--<li><a href="{{ route('register') }}"><b>Register</b></a></li>--}}
                {{--@else--}}
                    {{--<li class="dropdown">--}}
                        {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>--}}
                            {{--{{ Auth::users()->name }} <span class="caret"></span>--}}
                        {{--</a>--}}

                        {{--<ul class="dropdown-menu">--}}
                            {{--<li>--}}
                                {{--<a href="{{ route('logout') }}"--}}
                                   {{--onclick="event.preventDefault();--}}
                                                     {{--document.getElementById('logout-form').submit();">--}}
                                    {{--Logout--}}
                                {{--</a>--}}

                                {{--<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">--}}
                                    {{--{{ csrf_field() }}--}}
                                {{--</form>--}}
                            {{--</li>--}}
                        {{--</ul>--}}
                    {{--</li>--}}
                    {{--@endguest--}}
            {{--</ul>--}}
        </div>
    </div>
</nav>